Fixes ouroboros release
- Updates packaging scripts
- Adds loggregator common src
- Fixes volley json templating

[#130209605]

Signed-off-by: Jason Keene <jkeene@pivotal.io>

diff --git a/packages/ouroboros/packaging b/packages/ouroboros/packaging
--- a/packages/ouroboros/packaging
+++ b/packages/ouroboros/packaging
@@ -1,11 +1,12 @@
-set -e -x
+set -ex
+
+mkdir -p ${BOSH_INSTALL_TARGET}/src
+cp -a . ${BOSH_INSTALL_TARGET}/src
+export GOPATH=$BOSH_INSTALL_TARGET
 
 export GOROOT=$(readlink -nf /var/vcap/packages/golang1.7)
 export PATH=$GOROOT/bin:$PATH
+go install ouroboros
 
-cd ouroboros
-
-export GOPATH=$PWD
-
-go install github.com/cloudfoundry-incubator/ouroboros
-cp -a $PWD/bin/ouroboros ${BOSH_INSTALL_TARGET}
+# clean up source artifacts
+rm -rf ${BOSH_INSTALL_TARGET}/src ${BOSH_INSTALL_TARGET}/pkg
